apiVersion: v1
kind: Service
metadata:
  name: spring-boot-hibernate-demo
  labels:
    app: spring-boot-hibernate-demo
spec:
  type: NodePort
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8080
      nodePort: 30095
  selector:
    app: spring-boot-hibernate-demo
    tier: display
